### ISSUE TITLE
Compat with shield mechanics

### ISSUE THREAD

**Issue by VaIerka** [ToMe25/Better-Shields#2]
Hi. I'm using your mod in my modpack with shield mechanics mod ([https://www.curseforge.com/minecraft/mc-mods/shield-mechanics](url)) because it also has a couple of shields from other mods, so **customShieldMaxReduction** option is not realy enough to customize it all properly.
In this case, all three inscriptions are visible on the shield:
![2021-08-11_00 35 31](https://user-images.githubusercontent.com/80952503/128939009-3b2c9cba-703d-4c2a-b4e1-1c3820537079.png)
I tested it and it seems like shield always takes properties of lowest value (idk why). Could you pls add config option for disabling custom damageredution stats? Would be very nice, thanks

**Comment by ToMe25** [comment]
Someone already informed me about this issue on curseforge, and I do intend to add a config option to disable the damage reduction modifications of this mod.
However I unfortunately can't say when I will get around to adding that config option.

**Comment by ToMe25** [comment]
As of commit ae1e4d9 which is part of the latest release(1.14.4-1.3 and 1.16.X-1.2) there is now a config option to disable partial damage reduction.
There is no automatic integration for Shield Mechanics, because I believe the user should choose which mods partial damage reduction to disable, and because there is no good way to implement that without forcefully disabling this feature whenever shieldmechanics is detected.
