### ISSUE TITLE
[1.16.5] Random but frequent crash due to stack overflow on LivingEntity.sendImmune()

### ISSUE THREAD

**Issue by Colin-J-Wood** [ToMe25/Better-Shields#4]
[crash-2022-02-24_21.51.29-server.txt](https://github.com/ToMe25/Better-Shields/files/8136618/crash-2022-02-24_21.51.29-server.txt)

**Comment by Colin-J-Wood** [comment]
this isn't the only mod i have posted this on, as the stacktrace is not at all clear who is at fault.  am investigating with other devs and will let you know the result of this.

**Comment by Colin-J-Wood** [comment]
note that guardEntityTick was mentioned, which seems to be something your mod has provided

**Comment by ToMe25** [comment]
Before posting something like this please reproduce the crash with as few mods as possible!
Only post a crash report with a big mod list like this if you are unable to figure out which mods are responsible, and in that case please state this fact in the report!

Please link the other issues you opened about this here rather then just stating that you opened other Issues.
Also please add the following information to the Issue:
 * Minecraft version(Is fine this time because its in the title, but its good practice)
 * Forge version
 * Better Shields version
 * Other relevant mod versions(after reproducing with as few mods as possible)

I also doubt that this has anything to do with BetterShields since it does not modify any of the methods referenced in the stack trace.

**Comment by Colin-J-Wood** [comment]
closing issue after removing it fixed nothing.  gonna do some research for a while.
